const ORIGIN = 'https://heysmart.lv';

const MODELS = [
  { id: 'light2', slug: 'yandex-station-lite-2', aliases: ['лайт 2', 'light 2', 'light2', 'lite 2', 'lite2'], images: { blue: ['images/catalog/light-2/blue/01.webp'], violet: ['images/catalog/light-2/violet/01.webp'], green: ['images/catalog/light-2/green/01.webp'], pink: ['images/catalog/light-2/pink/01.webp'], coral: ['images/catalog/light-2/coral/01.webp'], black: ['images/catalog/light-2/black/01.webp'] }, copy: { ru: { name: 'Яндекс Станция Лайт 2', title: 'Купить Яндекс Станцию Лайт 2 в Риге — цена и наличие | HeySmart', description: 'Яндекс Станция Лайт 2 в Риге: актуальная цена, цвета в наличии, самовывоз по договорённости и помощь с настройкой.', intro: 'Компактная умная колонка с Алисой, LED-дисплеем и голосовым управлением для спальни, кухни или рабочего стола.', features: ['LED-дисплей', 'Голосовое управление', 'Музыка и подкасты', 'Управление совместимым умным домом'], fit: 'Подходит как первая Станция, для спальни, детской, кухни или небольшого рабочего места.', variants: 'Также её ищут как Станция Лайт 2, Алиса Лайт 2, Лайт 2, Лайт2, Yandex Station Lite 2 и Lite 2.' }, en: { name: 'Yandex Station Lite 2', title: 'Yandex Station Lite 2 in Riga — price and availability | HeySmart', description: 'Yandex Station Lite 2 in Riga: current price, available colours, pickup by arrangement and setup help.', intro: 'A compact smart speaker with Alice, an LED display and voice control for a bedroom, kitchen or desk.', features: ['LED display', 'Voice control', 'Music and podcasts', 'Compatible smart-home control'], fit: 'A good first Station for a bedroom, child’s room, kitchen or compact workspace.', variants: 'Also known as Station Lite 2, Lite 2, Lite2 and Alice Lite 2.' } } },
  { id: 'mini3', slug: 'yandex-station-mini-3', aliases: ['мини 3', 'mini 3', 'mini3'], images: { gray: ['images/catalog/mini-3/gray/01.webp'] }, copy: { ru: { name: 'Яндекс Станция Мини 3', title: 'Купить Яндекс Станцию Мини 3 в Риге — цена и наличие | HeySmart', description: 'Яндекс Станция Мини 3 в Риге: актуальная цена, наличие и помощь с выбором и настройкой.', intro: 'Компактная Станция с Алисой, LED-дисплеем и более собранным звучанием для ежедневного использования.', features: ['LED-дисплей', 'Сбалансированный звук', 'Таймеры и будильники', 'Голосовое управление'], fit: 'Подходит для кухни, спальни, кабинета или гостиной, когда нужна компактная колонка на каждый день.', variants: 'Её также называют Станция Мини 3, Алиса Мини 3, Мини 3, Мини3, Yandex Station Mini 3 и Mini3.' }, en: { name: 'Yandex Station Mini 3', title: 'Yandex Station Mini 3 in Riga — price and availability | HeySmart', description: 'Yandex Station Mini 3 in Riga: current price, availability, and help choosing and setting up.', intro: 'A compact Station with Alice, an LED display and balanced sound for everyday listening.', features: ['LED display', 'Balanced sound', 'Timers and alarms', 'Voice control'], fit: 'A compact everyday speaker for a kitchen, bedroom, office or living room.', variants: 'Also known as Station Mini 3, Mini 3, Mini3 and Alice Mini 3.' } } },
  { id: 'miniPro', slug: 'yandex-station-mini-3-pro', aliases: ['мини 3 про', 'мини про', 'mini 3 pro', 'mini3 pro', 'mini pro', 'minipro'], images: { green: ['images/catalog/mini-pro/green/01.webp'], blue: ['images/catalog/mini-pro/blue/01.webp'], gray: ['images/catalog/mini-pro/gray/01.webp'], graphite: ['images/catalog/mini-pro/graphite/01.png'] }, copy: { ru: { name: 'Яндекс Станция Мини 3 Про', title: 'Купить Яндекс Станцию Мини 3 Про в Риге — цена и наличие | HeySmart', description: 'Яндекс Станция Мини 3 Про в Риге: актуальная цена, наличие, Zigbee и помощь с настройкой.', intro: 'Компактная Станция с усиленным звуком, Zigbee и возможностями центра умного дома.', features: ['Усиленный звук', 'Zigbee', 'LED-дисплей', 'Сценарии умного дома'], fit: 'Подходит тем, кому нужен компактный формат с более широкими возможностями умного дома.', variants: 'Также известна как Станция Мини Про, Мини 3 Про, Мини3 Про, Mini 3 Pro, Mini3 Pro и Mini Pro.' }, en: { name: 'Yandex Station Mini 3 Pro', title: 'Yandex Station Mini 3 Pro in Riga — price and availability | HeySmart', description: 'Yandex Station Mini 3 Pro in Riga: current price, availability, Zigbee and setup help.', intro: 'A compact Station with stronger sound, Zigbee and smart-home hub features.', features: ['Stronger sound', 'Zigbee', 'LED display', 'Smart-home scenarios'], fit: 'For buyers who want a compact speaker with wider smart-home capabilities.', variants: 'Also known as Station Mini Pro, Mini 3 Pro, Mini3 Pro and Mini Pro.' } } },
  { id: 'street', slug: 'yandex-station-street', aliases: ['стрит', 'street'], images: { green: ['images/catalog/street/green/01.webp', 'images/catalog/street/green/02.webp', 'images/catalog/street/green/03.webp'], gray: ['images/catalog/street/gray/01.webp'], violet: ['images/catalog/street/violet/01.webp'], black: ['images/catalog/street/black/01.webp'] }, copy: { ru: { name: 'Яндекс Станция Стрит', title: 'Купить Яндекс Станцию Стрит в Риге — цена и наличие | HeySmart', description: 'Яндекс Станция Стрит в Риге: актуальная цена, наличие и помощь с выбором портативной колонки.', intro: 'Портативная Станция с аккумулятором, защитой от влаги и Bluetooth для дома, прогулок и поездок.', features: ['Встроенный аккумулятор', 'Bluetooth', 'Защита от влаги', 'Голосовое управление'], fit: 'Подходит для балкона, двора, поездок и ситуаций, где колонку хочется брать с собой.', variants: 'Её ищут как Станция Стрит, Яндекс Стрит, Алиса Стрит, Стрит, Yandex Station Street и Station Street.' }, en: { name: 'Yandex Station Street', title: 'Yandex Station Street in Riga — price and availability | HeySmart', description: 'Yandex Station Street in Riga: current price, availability and help choosing a portable speaker.', intro: 'A portable Station with a battery, moisture protection and Bluetooth for home, trips and time outside.', features: ['Built-in battery', 'Bluetooth', 'Moisture protection', 'Voice control'], fit: 'For a balcony, yard, trips, and use where you want to take the speaker with you.', variants: 'Also known as Station Street, Yandex Street, Street and Alice Street.' } } },
];

function normalize(value) { return String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ё/g, 'е').replace(/[^a-zа-я0-9]+/g, ' ').trim(); }
function findBySlug(slug) { return MODELS.find(model => model.slug === slug) || null; }
function findById(id) { return MODELS.find(model => model.id === id) || null; }
function modelProducts(model, products) { return (products || []).filter(product => { const text = normalize([product.productType, product.label, product.color].join(' ')); return model.aliases.some(alias => text.includes(normalize(alias))); }); }
function colorKey(model, product) { const text = normalize([product.color, product.label].join(' ')); return Object.keys(model.images).find(key => text.includes(normalize(key === 'gray' ? 'сер' : key === 'black' ? 'черн' : key === 'violet' ? 'фиолет' : key === 'green' ? 'зелен' : key === 'blue' ? 'голуб' : key === 'pink' ? 'розов' : key === 'coral' ? 'корал' : key))) || Object.keys(model.images)[0]; }
function absolute(asset) { return `${ORIGIN}/${asset}`; }
function escape(value) { return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function localizedColor(locale, value) { const map = { blue: ['Голубой', 'Blue'], green: ['Зелёный', 'Green'], pink: ['Розовый', 'Pink'], coral: ['Коралловый', 'Coral'], black: ['Чёрный', 'Black'], gray: ['Серый', 'Gray'], violet: ['Фиолетовый', 'Violet'], graphite: ['Графит', 'Graphite'] }; return (map[value] || [value, value])[locale === 'en' ? 1 : 0]; }
function build(model, products) { const stock = modelProducts(model, products).filter(product => (product.lots || []).reduce((sum, lot) => sum + (Number(lot.qty) || 0), 0) > 0).map(product => ({ ...product, colorKey: colorKey(model, product) })); const gallery = stock.flatMap(product => (model.images[product.colorKey] || []).map(image => ({ image, colorKey: product.colorKey }))); return { stock, prices: stock.map(product => Number(product.sellPrice) || 0).filter(Boolean), gallery: gallery.length ? gallery : Object.entries(model.images).slice(0, 1).flatMap(([colorKey, images]) => images.map(image => ({ image, colorKey }))), images: [...new Set(gallery.map(item => item.image))] }; }
function schema(model, locale, data, canonical) { const copy = model.copy[locale]; const available = data.stock.length > 0; const prices = data.prices; const offer = prices.length > 1 ? { '@type': 'AggregateOffer', priceCurrency: 'EUR', lowPrice: String(Math.min(...prices)), highPrice: String(Math.max(...prices)), offerCount: data.stock.length, availability: `https://schema.org/${available ? 'InStock' : 'OutOfStock'}`, url: canonical } : { '@type': 'Offer', priceCurrency: 'EUR', price: String(prices[0] || 0), availability: `https://schema.org/${available ? 'InStock' : 'OutOfStock'}`, url: canonical };
  return { '@context': 'https://schema.org', '@type': 'Product', '@id': `${canonical}#product`, name: copy.name, url: canonical, image: (data.images.length ? data.images : Object.values(model.images).flat()).map(absolute), description: copy.intro, sku: data.stock.map(product => product.id).join(', ') || undefined, offers: offer };
}
function render(model, locale, products) { const copy = model.copy[locale]; const canonical = `${ORIGIN}/${locale}/${model.slug}`; const alternate = `${ORIGIN}/${locale === 'ru' ? 'en' : 'ru'}/${model.slug}`; const data = build(model, products); const prices = data.prices; const price = prices.length ? `${prices.length > 1 ? (locale === 'en' ? 'From ' : 'От ') : ''}${Math.min(...prices).toLocaleString(locale === 'en' ? 'en-US' : 'ru-RU')} €` : (locale === 'en' ? 'Currently unavailable' : 'Сейчас нет в наличии'); const status = data.stock.length ? (locale === 'en' ? 'In stock' : 'В наличии') : (locale === 'en' ? 'Currently unavailable' : 'Сейчас нет в наличии'); const catalog = `/${locale}`; const help = locale === 'ru' ? '<p><a href="/ru/help/rabotaet-li-alisa-v-latvii">Работает ли Алиса в Латвии?</a> · <a href="/ru/help/nuzhna-li-podpiska-yandex-plus">Нужна ли подписка Яндекс Плюс?</a></p>' : ''; const gallery = data.gallery.map((item, index) => `<a class="product-image-link" href="${catalog}#model=${encodeURIComponent(model.id)}&color=${encodeURIComponent(item.colorKey)}" aria-label="${escape(locale === 'en' ? `Select ${localizedColor(locale, item.colorKey)}` : `Выбрать цвет: ${localizedColor(locale, item.colorKey)}`)}"><img src="/${escape(item.image)}" alt="${escape(`${copy.name}, ${localizedColor(locale, item.colorKey)}`)}" loading="${index ? 'lazy' : 'eager'}"></a>`).join(''); const colors = data.stock.length ? `<ul>${data.stock.map(product => `<li>${escape(localizedColor(locale, product.colorKey))} — ${escape(String(Number(product.sellPrice) || 0))} €</li>`).join('')}</ul>` : `<p>${escape(status)}</p>`;
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(copy.title)}</title><meta name="description" content="${escape(copy.description)}"><meta name="robots" content="index, follow"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="${locale}" href="${canonical}"><link rel="alternate" hreflang="${locale === 'ru' ? 'en' : 'ru'}" href="${alternate}"><link rel="stylesheet" href="/catalog.css"><script type="application/ld+json">${JSON.stringify(schema(model, locale, data, canonical)).replace(/</g, '\\u003c')}</script></head><body><main class="product-page"><header class="site-header"><a href="${catalog}">HeySmart</a><nav><a href="${catalog}">${locale === 'en' ? 'Catalog' : 'Каталог'}</a> <a href="${alternate.replace(ORIGIN, '')}" hreflang="${locale === 'ru' ? 'en' : 'ru'}">${locale === 'ru' ? 'EN' : 'RU'}</a></nav></header><article><p class="eyebrow">HeySmart</p><h1>${escape(copy.name)}</h1><p class="line">${escape(copy.intro)}</p><p class="product-price">${escape(price)}</p><p class="product-stock">${escape(status)}</p><div class="product-gallery">${gallery}</div><section><h2>${locale === 'en' ? 'Key features' : 'Главное'}</h2><ul>${copy.features.map(feature => `<li>${escape(feature)}</li>`).join('')}</ul></section><section><h2>${locale === 'en' ? 'Who it suits' : 'Кому подойдёт'}</h2><p>${escape(copy.fit)}</p></section><section><h2>${locale === 'en' ? 'Available colours and prices' : 'Цвета и цены в наличии'}</h2>${colors}</section><section><h2>${locale === 'en' ? 'Buying and setup in Latvia' : 'Покупка и настройка в Латвии'}</h2><p>${locale === 'en' ? 'Pickup in Riga is arranged in advance. We can help choose a model and explain the basic setup with Wi-Fi, an account and the app.' : 'Самовывоз в Риге согласуем заранее. Поможем выбрать модель и подскажем базовую настройку с Wi‑Fi, аккаунтом и приложением.'}</p>${help}</section><p class="product-variants">${escape(copy.variants)}</p><p><a href="${catalog}">${locale === 'en' ? 'Back to catalog' : 'Вернуться в каталог'}</a></p></article></main></body></html>`;
}
function sitemapUrls() { return MODELS.flatMap(model => ['ru', 'en'].map(locale => ({ loc: `${ORIGIN}/${locale}/${model.slug}`, lastmod: '2026-09-03' }))); }
function catalogItemList(locale, canonical) { return { '@context': 'https://schema.org', '@graph': [{ '@type': 'WebPage', '@id': `${canonical}#webpage`, url: canonical, inLanguage: locale }, { '@type': 'ItemList', '@id': `${canonical}#catalog`, name: locale === 'en' ? 'HeySmart catalog' : 'Каталог HeySmart', itemListElement: MODELS.map((model, index) => ({ '@type': 'ListItem', position: index + 1, url: `${ORIGIN}/${locale}/${model.slug}`, name: model.copy[locale].name })) }] }; }
module.exports = { MODELS, findBySlug, findById, render, sitemapUrls, catalogItemList };
